module Believe
  module Models
    module Coaching
      type principle_get_random_params = ({} & ::Believe::Internal::Type::request_parameters)

      class PrincipleGetRandomParams < ::Believe::Internal::Type::BaseModel
        extend ::Believe::Internal::Type::RequestParameters::Converter
        include ::Believe::Internal::Type::RequestParameters

        def initialize: (?request_options: ::Believe::request_opts) -> void

        def to_hash: () -> {request_options: ::Believe::RequestOptions}
      end
    end
  end
end
