module Believe
  class BelieveSubmitParams = Believe::Models::BelieveSubmitParams

  class Biscuit = Believe::Models::Biscuit

  class BiscuitGetFreshParams = Believe::Models::BiscuitGetFreshParams

  class BiscuitListParams = Believe::Models::BiscuitListParams

  class BiscuitRetrieveParams = Believe::Models::BiscuitRetrieveParams

  class Character = Believe::Models::Character

  class CharacterCreateParams = Believe::Models::CharacterCreateParams

  class CharacterDeleteParams = Believe::Models::CharacterDeleteParams

  class CharacterGetQuotesParams = Believe::Models::CharacterGetQuotesParams

  class CharacterListParams = Believe::Models::CharacterListParams

  class CharacterRetrieveParams = Believe::Models::CharacterRetrieveParams

  module CharacterRole = Believe::Models::CharacterRole

  class CharacterUpdateParams = Believe::Models::CharacterUpdateParams

  class Coach = Believe::Models::Coach

  module Coaching = Believe::Models::Coaching

  module CoachSpecialty = Believe::Models::CoachSpecialty

  class ConflictResolveParams = Believe::Models::ConflictResolveParams

  class EmotionalStats = Believe::Models::EmotionalStats

  class Episode = Believe::Models::Episode

  class EpisodeCreateParams = Believe::Models::EpisodeCreateParams

  class EpisodeDeleteParams = Believe::Models::EpisodeDeleteParams

  class EpisodeGetWisdomParams = Believe::Models::EpisodeGetWisdomParams

  class EpisodeListParams = Believe::Models::EpisodeListParams

  class EpisodeRetrieveParams = Believe::Models::EpisodeRetrieveParams

  class EpisodeUpdateParams = Believe::Models::EpisodeUpdateParams

  class EquipmentManager = Believe::Models::EquipmentManager

  class GeoLocation = Believe::Models::GeoLocation

  class GrowthArc = Believe::Models::GrowthArc

  module League = Believe::Models::League

  class Match = Believe::Models::Match

  class MatchCreateParams = Believe::Models::MatchCreateParams

  class MatchDeleteParams = Believe::Models::MatchDeleteParams

  module Matches = Believe::Models::Matches

  class MatchGetLessonParams = Believe::Models::MatchGetLessonParams

  class MatchGetTurningPointsParams = Believe::Models::MatchGetTurningPointsParams

  class MatchListParams = Believe::Models::MatchListParams

  module MatchResult = Believe::Models::MatchResult

  class MatchRetrieveParams = Believe::Models::MatchRetrieveParams

  class MatchStreamLiveParams = Believe::Models::MatchStreamLiveParams

  module MatchType = Believe::Models::MatchType

  class MatchUpdateParams = Believe::Models::MatchUpdateParams

  module MedicalSpecialty = Believe::Models::MedicalSpecialty

  class MedicalStaff = Believe::Models::MedicalStaff

  class PaginatedResponse = Believe::Models::PaginatedResponse

  class PaginatedResponseQuote = Believe::Models::PaginatedResponseQuote

  class PepTalkRetrieveParams = Believe::Models::PepTalkRetrieveParams

  class Player = Believe::Models::Player

  module Position = Believe::Models::Position

  class PressSimulateParams = Believe::Models::PressSimulateParams

  class Quote = Believe::Models::Quote

  class QuoteCreateParams = Believe::Models::QuoteCreateParams

  class QuoteDeleteParams = Believe::Models::QuoteDeleteParams

  class QuoteGetRandomParams = Believe::Models::QuoteGetRandomParams

  class QuoteListByCharacterParams = Believe::Models::QuoteListByCharacterParams

  class QuoteListByThemeParams = Believe::Models::QuoteListByThemeParams

  class QuoteListParams = Believe::Models::QuoteListParams

  module QuoteMoment = Believe::Models::QuoteMoment

  class QuoteRetrieveParams = Believe::Models::QuoteRetrieveParams

  module QuoteTheme = Believe::Models::QuoteTheme

  class QuoteUpdateParams = Believe::Models::QuoteUpdateParams

  class ReframeTransformNegativeThoughtsParams = Believe::Models::ReframeTransformNegativeThoughtsParams

  class StreamTestConnectionParams = Believe::Models::StreamTestConnectionParams

  class Team = Believe::Models::Team

  class TeamCreateParams = Believe::Models::TeamCreateParams

  class TeamDeleteParams = Believe::Models::TeamDeleteParams

  class TeamGetCultureParams = Believe::Models::TeamGetCultureParams

  class TeamGetRivalsParams = Believe::Models::TeamGetRivalsParams

  class TeamListLogosParams = Believe::Models::TeamListLogosParams

  class TeamListParams = Believe::Models::TeamListParams

  class TeamMemberCreateParams = Believe::Models::TeamMemberCreateParams

  class TeamMemberDeleteParams = Believe::Models::TeamMemberDeleteParams

  class TeamMemberListCoachesParams = Believe::Models::TeamMemberListCoachesParams

  class TeamMemberListParams = Believe::Models::TeamMemberListParams

  class TeamMemberListPlayersParams = Believe::Models::TeamMemberListPlayersParams

  class TeamMemberListStaffParams = Believe::Models::TeamMemberListStaffParams

  class TeamMemberRetrieveParams = Believe::Models::TeamMemberRetrieveParams

  class TeamMemberUpdateParams = Believe::Models::TeamMemberUpdateParams

  class TeamRetrieveParams = Believe::Models::TeamRetrieveParams

  module Teams = Believe::Models::Teams

  class TeamUpdateParams = Believe::Models::TeamUpdateParams

  class TeamValues = Believe::Models::TeamValues

  class TurningPoint = Believe::Models::TurningPoint
end
