module Believe
  module Internal
    class SkipLimitPage[Elem]
      include ::Believe::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor total: Integer

      attr_accessor skip: Integer

      def inspect: () -> String
    end
  end
end
