#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	test/believe/resources/characters_test.rb
	test/believe/resources/teams_test.rb
	test/believe/resources/teams/logo_test.rb
	test/believe/resources/matches_test.rb
	test/believe/resources/matches/commentary_test.rb
	test/believe/resources/episodes_test.rb
	test/believe/resources/quotes_test.rb
	test/believe/resources/believe_test.rb
	test/believe/resources/conflicts_test.rb
	test/believe/resources/reframe_test.rb
	test/believe/resources/press_test.rb
	test/believe/resources/coaching_test.rb
	test/believe/resources/coaching/principles_test.rb
	test/believe/resources/biscuits_test.rb
	test/believe/resources/pep_talk_test.rb
	test/believe/resources/stream_test.rb
	test/believe/resources/team_members_test.rb
	test/believe/resources/webhooks_test.rb
	test/believe/resources/health_test.rb
	test/believe/resources/version_test.rb
	test/believe/resources/client_test.rb
	test/believe/resources/client/ws_test.rb
	test/believe/resources/client/ticket_sales_test.rb
	test/believe/client_test.rb
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Instead of running the tests, use the linter to check if an
# older test is no longer compatible with the latest SDK.
./scripts/lint
