module Believe
  module Models
    type believe_submit_response = {
      action_suggestion: String,
      believe_score: Integer,
      goldfish_wisdom: String,
      relevant_quote: String,
      ted_response: String
    }

    class BelieveSubmitResponse < ::Believe::Internal::Type::BaseModel
      attr_accessor action_suggestion: String

      attr_accessor believe_score: Integer

      attr_accessor goldfish_wisdom: String

      attr_accessor relevant_quote: String

      attr_accessor ted_response: String

      def initialize: (action_suggestion: String, believe_score: Integer, goldfish_wisdom: String, relevant_quote: String, ted_response: String) -> void

      def to_hash: () -> {
        action_suggestion: String,
        believe_score: Integer,
        goldfish_wisdom: String,
        relevant_quote: String,
        ted_response: String
      }
    end
  end
end
