module Believe
  module Models
    type believe_submit_params =
      {
        situation: String,
        situation_type: Believe::Models::BelieveSubmitParams::situation_type,
        context: String?,
        intensity: Integer
      }
      & Believe::Internal::Type::request_parameters

    class BelieveSubmitParams < Believe::Internal::Type::BaseModel
      extend Believe::Internal::Type::RequestParameters::Converter
      include Believe::Internal::Type::RequestParameters

      attr_accessor situation: String

      attr_accessor situation_type: Believe::Models::BelieveSubmitParams::situation_type

      attr_accessor context: String?

      attr_reader intensity: Integer?

      def intensity=: (Integer) -> Integer

      def initialize: (
        situation: String,
        situation_type: Believe::Models::BelieveSubmitParams::situation_type,
        ?context: String?,
        ?intensity: Integer,
        ?request_options: Believe::request_opts
      ) -> void

      def to_hash: -> {
        situation: String,
        situation_type: Believe::Models::BelieveSubmitParams::situation_type,
        context: String?,
        intensity: Integer,
        request_options: Believe::RequestOptions
      }

      type situation_type =
        :work_challenge
        | :personal_setback
        | :team_conflict
        | :self_doubt
        | :big_decision
        | :failure
        | :new_beginning
        | :relationship

      module SituationType
        extend Believe::Internal::Type::Enum

        WORK_CHALLENGE: :work_challenge
        PERSONAL_SETBACK: :personal_setback
        TEAM_CONFLICT: :team_conflict
        SELF_DOUBT: :self_doubt
        BIG_DECISION: :big_decision
        FAILURE: :failure
        NEW_BEGINNING: :new_beginning
        RELATIONSHIP: :relationship

        def self?.values: -> ::Array[Believe::Models::BelieveSubmitParams::situation_type]
      end
    end
  end
end
