module Believe
  module Models
    type biscuit_retrieve_params = ({biscuit_id: String} & ::Believe::Internal::Type::request_parameters)

    class BiscuitRetrieveParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor biscuit_id: String

      def initialize: (biscuit_id: String, ?request_options: ::Believe::request_opts) -> void

      def to_hash: () -> {biscuit_id: String, request_options: ::Believe::RequestOptions}
    end
  end
end
