module Believe
  module Models
    type coach =
      {
        id: String,
        character_id: String,
        specialty: Believe::Models::coach_specialty,
        team_id: String,
        years_with_team: Integer,
        certifications: ::Array[String],
        member_type: Believe::Models::Coach::member_type,
        win_rate: Float?
      }

    class Coach < Believe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor character_id: String

      attr_accessor specialty: Believe::Models::coach_specialty

      attr_accessor team_id: String

      attr_accessor years_with_team: Integer

      attr_reader certifications: ::Array[String]?

      def certifications=: (::Array[String]) -> ::Array[String]

      attr_reader member_type: Believe::Models::Coach::member_type?

      def member_type=: (
        Believe::Models::Coach::member_type
      ) -> Believe::Models::Coach::member_type

      attr_accessor win_rate: Float?

      def initialize: (
        id: String,
        character_id: String,
        specialty: Believe::Models::coach_specialty,
        team_id: String,
        years_with_team: Integer,
        ?certifications: ::Array[String],
        ?member_type: Believe::Models::Coach::member_type,
        ?win_rate: Float?
      ) -> void

      def to_hash: -> {
        id: String,
        character_id: String,
        specialty: Believe::Models::coach_specialty,
        team_id: String,
        years_with_team: Integer,
        certifications: ::Array[String],
        member_type: Believe::Models::Coach::member_type,
        win_rate: Float?
      }

      type member_type = :coach

      module MemberType
        extend Believe::Internal::Type::Enum

        COACH: :coach

        def self?.values: -> ::Array[Believe::Models::Coach::member_type]
      end
    end
  end
end
