module Believe
  module Models
    type coach_specialty = (:head_coach | :assistant_coach | :goalkeeping_coach | :fitness_coach | :tactical_analyst)

    module CoachSpecialty
      extend ::Believe::Internal::Type::Enum

      HEAD_COACH: :head_coach
      ASSISTANT_COACH: :assistant_coach
      GOALKEEPING_COACH: :goalkeeping_coach
      FITNESS_COACH: :fitness_coach
      TACTICAL_ANALYST: :tactical_analyst

      def self?.values: () -> ::Array[::Believe::Models::coach_specialty]
    end
  end
end
