module Believe
  module Models
    type conflict_resolve_params =
      {
        conflict_type: Believe::Models::ConflictResolveParams::conflict_type,
        description: String,
        parties_involved: ::Array[String],
        attempts_made: ::Array[String]?
      }
      & Believe::Internal::Type::request_parameters

    class ConflictResolveParams < Believe::Internal::Type::BaseModel
      extend Believe::Internal::Type::RequestParameters::Converter
      include Believe::Internal::Type::RequestParameters

      attr_accessor conflict_type: Believe::Models::ConflictResolveParams::conflict_type

      attr_accessor description: String

      attr_accessor parties_involved: ::Array[String]

      attr_accessor attempts_made: ::Array[String]?

      def initialize: (
        conflict_type: Believe::Models::ConflictResolveParams::conflict_type,
        description: String,
        parties_involved: ::Array[String],
        ?attempts_made: ::Array[String]?,
        ?request_options: Believe::request_opts
      ) -> void

      def to_hash: -> {
        conflict_type: Believe::Models::ConflictResolveParams::conflict_type,
        description: String,
        parties_involved: ::Array[String],
        attempts_made: ::Array[String]?,
        request_options: Believe::RequestOptions
      }

      type conflict_type =
        :interpersonal
        | :team_dynamics
        | :leadership
        | :ego
        | :miscommunication
        | :competition

      module ConflictType
        extend Believe::Internal::Type::Enum

        INTERPERSONAL: :interpersonal
        TEAM_DYNAMICS: :team_dynamics
        LEADERSHIP: :leadership
        EGO: :ego
        MISCOMMUNICATION: :miscommunication
        COMPETITION: :competition

        def self?.values: -> ::Array[Believe::Models::ConflictResolveParams::conflict_type]
      end
    end
  end
end
