module Believe
  module Models
    type episode_list_params = ({character_focus: String?, limit: Integer, season: Integer?, skip: Integer} & ::Believe::Internal::Type::request_parameters)

    class EpisodeListParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor character_focus: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor season: Integer?

      attr_reader skip: Integer?

      def skip=: (Integer) -> Integer

      def initialize: (?character_focus: String?, ?limit: Integer, ?season: Integer?, ?skip: Integer, ?request_options: ::Believe::request_opts) -> void

      def to_hash: () -> {
        character_focus: String?,
        limit: Integer,
        season: Integer?,
        skip: Integer,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
