module Believe
  module Models
    type episode_get_wisdom_params = ({episode_id: String} & ::Believe::Internal::Type::request_parameters)

    class EpisodeGetWisdomParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor episode_id: String

      def initialize: (episode_id: String, ?request_options: ::Believe::request_opts) -> void

      def to_hash: () -> {episode_id: String, request_options: ::Believe::RequestOptions}
    end
  end
end
