module Believe
  module Models
    type equipment_manager =
      {
        id: String,
        character_id: String,
        team_id: String,
        years_with_team: Integer,
        is_head_kitman: bool,
        member_type: ::Believe::Models::EquipmentManager::member_type,
        responsibilities: ::Array[String]
      }

    class EquipmentManager < ::Believe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor character_id: String

      attr_accessor team_id: String

      attr_accessor years_with_team: Integer

      attr_reader is_head_kitman: bool?

      def is_head_kitman=: (bool) -> bool

      attr_reader member_type: ::Believe::Models::EquipmentManager::member_type?

      def member_type=: (
        ::Believe::Models::EquipmentManager::member_type
      ) -> ::Believe::Models::EquipmentManager::member_type

      attr_reader responsibilities: ::Array[String]?

      def responsibilities=: (::Array[String]) -> ::Array[String]

      def initialize: (
        id: String,
        character_id: String,
        team_id: String,
        years_with_team: Integer,
        ?is_head_kitman: bool,
        ?member_type: ::Believe::Models::EquipmentManager::member_type,
        ?responsibilities: ::Array[String]
      ) -> void

      def to_hash: -> {
        id: String,
        character_id: String,
        team_id: String,
        years_with_team: Integer,
        is_head_kitman: bool,
        member_type: ::Believe::Models::EquipmentManager::member_type,
        responsibilities: ::Array[String]
      }

      type member_type = :equipment_manager

      module MemberType
        extend ::Believe::Internal::Type::Enum

        EQUIPMENT_MANAGER: :equipment_manager

        def self?.values: -> ::Array[::Believe::Models::EquipmentManager::member_type]
      end
    end
  end
end
