module Believe
  module Models
    type geo_location = {latitude: Float, longitude: Float}

    class GeoLocation < ::Believe::Internal::Type::BaseModel
      attr_accessor latitude: Float

      attr_accessor longitude: Float

      def initialize: (latitude: Float, longitude: Float) -> void

      def to_hash: () -> {latitude: Float, longitude: Float}
    end
  end
end
