module Believe
  module Models
    type match_update_params = ({
      match_id: String,
      attendance: Integer?,
      away_score: Integer?,
      away_team_id: String?,
      date: Time?,
      episode_id: String?,
      home_score: Integer?,
      home_team_id: String?,
      lesson_learned: String?,
      match_type: ::Believe::Models::match_type?,
      possession_percentage: Float?,
      result: ::Believe::Models::match_result?,
      ted_halftime_speech: String?,
      ticket_revenue_gbp: ::Believe::Models::MatchUpdateParams::ticket_revenue_gbp?,
      turning_points: ::Array[::Believe::TurningPoint]?,
      weather_temp_celsius: Float?
    } & ::Believe::Internal::Type::request_parameters)

    class MatchUpdateParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor match_id: String

      attr_accessor attendance: Integer?

      attr_accessor away_score: Integer?

      attr_accessor away_team_id: String?

      attr_accessor date: Time?

      attr_accessor episode_id: String?

      attr_accessor home_score: Integer?

      attr_accessor home_team_id: String?

      attr_accessor lesson_learned: String?

      attr_accessor match_type: ::Believe::Models::match_type?

      attr_accessor possession_percentage: Float?

      attr_accessor result: ::Believe::Models::match_result?

      attr_accessor ted_halftime_speech: String?

      attr_accessor ticket_revenue_gbp: ::Believe::Models::MatchUpdateParams::ticket_revenue_gbp?

      attr_accessor turning_points: ::Array[::Believe::TurningPoint]?

      attr_accessor weather_temp_celsius: Float?

      def initialize: (match_id: String, ?attendance: Integer?, ?away_score: Integer?, ?away_team_id: String?, ?date: Time?, ?episode_id: String?, ?home_score: Integer?, ?home_team_id: String?, ?lesson_learned: String?, ?match_type: ::Believe::Models::match_type?, ?possession_percentage: Float?, ?result: ::Believe::Models::match_result?, ?ted_halftime_speech: String?, ?ticket_revenue_gbp: ::Believe::Models::MatchUpdateParams::ticket_revenue_gbp?, ?turning_points: ::Array[::Believe::TurningPoint]?, ?weather_temp_celsius: Float?, ?request_options: ::Believe::request_opts) -> void

      def to_hash: () -> {
        match_id: String,
        attendance: Integer?,
        away_score: Integer?,
        away_team_id: String?,
        date: Time?,
        episode_id: String?,
        home_score: Integer?,
        home_team_id: String?,
        lesson_learned: String?,
        match_type: ::Believe::Models::match_type?,
        possession_percentage: Float?,
        result: ::Believe::Models::match_result?,
        ted_halftime_speech: String?,
        ticket_revenue_gbp: ::Believe::Models::MatchUpdateParams::ticket_revenue_gbp?,
        turning_points: ::Array[::Believe::TurningPoint]?,
        weather_temp_celsius: Float?,
        request_options: ::Believe::RequestOptions
      }

      type ticket_revenue_gbp = (Float | String)

      module TicketRevenueGbp
        extend ::Believe::Internal::Type::Union

        def self?.variants: () -> ::Array[::Believe::Models::MatchUpdateParams::ticket_revenue_gbp]
      end
    end
  end
end
