module Believe
  module Models
    type match = {
      id: String,
      away_team_id: String,
      date: Time,
      home_team_id: String,
      match_type: ::Believe::Models::match_type,
      attendance: Integer?,
      away_score: Integer,
      episode_id: String?,
      home_score: Integer,
      lesson_learned: String?,
      possession_percentage: Float?,
      result: ::Believe::Models::match_result,
      ted_halftime_speech: String?,
      ticket_revenue_gbp: String?,
      turning_points: ::Array[::Believe::TurningPoint],
      weather_temp_celsius: Float?
    }

    class Match < ::Believe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor away_team_id: String

      attr_accessor date: Time

      attr_accessor home_team_id: String

      attr_accessor match_type: ::Believe::Models::match_type

      attr_accessor attendance: Integer?

      attr_reader away_score: Integer?

      def away_score=: (Integer) -> Integer

      attr_accessor episode_id: String?

      attr_reader home_score: Integer?

      def home_score=: (Integer) -> Integer

      attr_accessor lesson_learned: String?

      attr_accessor possession_percentage: Float?

      attr_reader result: ::Believe::Models::match_result?

      def result=: (::Believe::Models::match_result) -> ::Believe::Models::match_result

      attr_accessor ted_halftime_speech: String?

      attr_accessor ticket_revenue_gbp: String?

      attr_reader turning_points: ::Array[::Believe::TurningPoint]?

      def turning_points=: (::Array[::Believe::TurningPoint]) -> ::Array[::Believe::TurningPoint]

      attr_accessor weather_temp_celsius: Float?

      def initialize: (id: String, away_team_id: String, date: Time, home_team_id: String, match_type: ::Believe::Models::match_type, ?attendance: Integer?, ?away_score: Integer, ?episode_id: String?, ?home_score: Integer, ?lesson_learned: String?, ?possession_percentage: Float?, ?result: ::Believe::Models::match_result, ?ted_halftime_speech: String?, ?ticket_revenue_gbp: String?, ?turning_points: ::Array[::Believe::TurningPoint], ?weather_temp_celsius: Float?) -> void

      def to_hash: () -> {
        id: String,
        away_team_id: String,
        date: Time,
        home_team_id: String,
        match_type: ::Believe::Models::match_type,
        attendance: Integer?,
        away_score: Integer,
        episode_id: String?,
        home_score: Integer,
        lesson_learned: String?,
        possession_percentage: Float?,
        result: ::Believe::Models::match_result,
        ted_halftime_speech: String?,
        ticket_revenue_gbp: String?,
        turning_points: ::Array[::Believe::TurningPoint],
        weather_temp_celsius: Float?
      }
    end
  end
end
