module Believe
  module Models
    type match_stream_live_params = ({away_team: String, excitement_level: Integer, home_team: String, speed: Float} & ::Believe::Internal::Type::request_parameters)

    class MatchStreamLiveParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_reader away_team: String?

      def away_team=: (String) -> String

      attr_reader excitement_level: Integer?

      def excitement_level=: (Integer) -> Integer

      attr_reader home_team: String?

      def home_team=: (String) -> String

      attr_reader speed: Float?

      def speed=: (Float) -> Float

      def initialize: (?away_team: String, ?excitement_level: Integer, ?home_team: String, ?speed: Float, ?request_options: ::Believe::request_opts) -> void

      def to_hash: () -> {
        away_team: String,
        excitement_level: Integer,
        home_team: String,
        speed: Float,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
