module Believe
  module Models
    type match_type = :league | :cup | :friendly | :playoff | :final

    module MatchType
      extend ::Believe::Internal::Type::Enum

      LEAGUE: :league
      CUP: :cup
      FRIENDLY: :friendly
      PLAYOFF: :playoff
      FINAL: :final

      def self?.values: -> ::Array[::Believe::Models::match_type]
    end
  end
end
