module Believe
  module Models
    type medical_specialty =
      :team_doctor
      | :physiotherapist
      | :sports_psychologist
      | :nutritionist
      | :massage_therapist

    module MedicalSpecialty
      extend ::Believe::Internal::Type::Enum

      TEAM_DOCTOR: :team_doctor
      PHYSIOTHERAPIST: :physiotherapist
      SPORTS_PSYCHOLOGIST: :sports_psychologist
      NUTRITIONIST: :nutritionist
      MASSAGE_THERAPIST: :massage_therapist

      def self?.values: -> ::Array[::Believe::Models::medical_specialty]
    end
  end
end
