module Believe
  module Models
    type medical_staff = {
      id: String,
      character_id: String,
      specialty: ::Believe::Models::medical_specialty,
      team_id: String,
      years_with_team: Integer,
      license_number: String?,
      member_type: ::Believe::Models::MedicalStaff::member_type,
      qualifications: ::Array[String]
    }

    class MedicalStaff < ::Believe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor character_id: String

      attr_accessor specialty: ::Believe::Models::medical_specialty

      attr_accessor team_id: String

      attr_accessor years_with_team: Integer

      attr_accessor license_number: String?

      attr_reader member_type: ::Believe::Models::MedicalStaff::member_type?

      def member_type=: (::Believe::Models::MedicalStaff::member_type) -> ::Believe::Models::MedicalStaff::member_type

      attr_reader qualifications: ::Array[String]?

      def qualifications=: (::Array[String]) -> ::Array[String]

      def initialize: (id: String, character_id: String, specialty: ::Believe::Models::medical_specialty, team_id: String, years_with_team: Integer, ?license_number: String?, ?member_type: ::Believe::Models::MedicalStaff::member_type, ?qualifications: ::Array[String]) -> void

      def to_hash: () -> {
        id: String,
        character_id: String,
        specialty: ::Believe::Models::medical_specialty,
        team_id: String,
        years_with_team: Integer,
        license_number: String?,
        member_type: ::Believe::Models::MedicalStaff::member_type,
        qualifications: ::Array[String]
      }

      type member_type = :medical_staff

      module MemberType
        extend ::Believe::Internal::Type::Enum

        MEDICAL_STAFF: :medical_staff

        def self?.values: () -> ::Array[::Believe::Models::MedicalStaff::member_type]
      end
    end
  end
end
