module Believe
  module Models
    type pep_talk_retrieve_response =
      {
        chunks: ::Array[Believe::Models::PepTalkRetrieveResponse::Chunk],
        text: String
      }

    class PepTalkRetrieveResponse < Believe::Internal::Type::BaseModel
      attr_accessor chunks: ::Array[Believe::Models::PepTalkRetrieveResponse::Chunk]

      attr_accessor text: String

      def initialize: (
        chunks: ::Array[Believe::Models::PepTalkRetrieveResponse::Chunk],
        text: String
      ) -> void

      def to_hash: -> {
        chunks: ::Array[Believe::Models::PepTalkRetrieveResponse::Chunk],
        text: String
      }

      type chunk =
        {
          chunk_id: Integer,
          is_final: bool,
          text: String,
          emotional_beat: String?
        }

      class Chunk < Believe::Internal::Type::BaseModel
        attr_accessor chunk_id: Integer

        attr_accessor is_final: bool

        attr_accessor text: String

        attr_accessor emotional_beat: String?

        def initialize: (
          chunk_id: Integer,
          is_final: bool,
          text: String,
          ?emotional_beat: String?
        ) -> void

        def to_hash: -> {
          chunk_id: Integer,
          is_final: bool,
          text: String,
          emotional_beat: String?
        }
      end
    end
  end
end
