module Believe
  module Models
    type press_simulate_params =
      { question: String, hostile: bool, topic: String? }
      & ::Believe::Internal::Type::request_parameters

    class PressSimulateParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor question: String

      attr_reader hostile: bool?

      def hostile=: (bool) -> bool

      attr_accessor topic: String?

      def initialize: (
        question: String,
        ?hostile: bool,
        ?topic: String?,
        ?request_options: ::Believe::request_opts
      ) -> void

      def to_hash: -> {
        question: String,
        hostile: bool,
        topic: String?,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
