module Believe
  module Models
    type quote_list_by_character_params =
      { character_id: String, limit: Integer, skip: Integer }
      & ::Believe::Internal::Type::request_parameters

    class QuoteListByCharacterParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor character_id: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader skip: Integer?

      def skip=: (Integer) -> Integer

      def initialize: (
        character_id: String,
        ?limit: Integer,
        ?skip: Integer,
        ?request_options: ::Believe::request_opts
      ) -> void

      def to_hash: -> {
        character_id: String,
        limit: Integer,
        skip: Integer,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
