module Believe
  module Models
    type quote_create_params =
      {
        character_id: String,
        context: String,
        moment_type: ::Believe::Models::quote_moment,
        text: String,
        theme: ::Believe::Models::quote_theme,
        episode_id: String?,
        is_funny: bool,
        is_inspirational: bool,
        popularity_score: Float?,
        secondary_themes: ::Array[::Believe::Models::quote_theme],
        times_shared: Integer?
      }
      & ::Believe::Internal::Type::request_parameters

    class QuoteCreateParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor character_id: String

      attr_accessor context: String

      attr_accessor moment_type: ::Believe::Models::quote_moment

      attr_accessor text: String

      attr_accessor theme: ::Believe::Models::quote_theme

      attr_accessor episode_id: String?

      attr_reader is_funny: bool?

      def is_funny=: (bool) -> bool

      attr_reader is_inspirational: bool?

      def is_inspirational=: (bool) -> bool

      attr_accessor popularity_score: Float?

      attr_reader secondary_themes: ::Array[::Believe::Models::quote_theme]?

      def secondary_themes=: (
        ::Array[::Believe::Models::quote_theme]
      ) -> ::Array[::Believe::Models::quote_theme]

      attr_accessor times_shared: Integer?

      def initialize: (
        character_id: String,
        context: String,
        moment_type: ::Believe::Models::quote_moment,
        text: String,
        theme: ::Believe::Models::quote_theme,
        ?episode_id: String?,
        ?is_funny: bool,
        ?is_inspirational: bool,
        ?popularity_score: Float?,
        ?secondary_themes: ::Array[::Believe::Models::quote_theme],
        ?times_shared: Integer?,
        ?request_options: ::Believe::request_opts
      ) -> void

      def to_hash: -> {
        character_id: String,
        context: String,
        moment_type: ::Believe::Models::quote_moment,
        text: String,
        theme: ::Believe::Models::quote_theme,
        episode_id: String?,
        is_funny: bool,
        is_inspirational: bool,
        popularity_score: Float?,
        secondary_themes: ::Array[::Believe::Models::quote_theme],
        times_shared: Integer?,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
