module Believe
  module Models
    type registered_webhook =
      {
        id: String,
        created_at: Time,
        event_types: ::Array[::Believe::Models::RegisteredWebhook::event_type],
        secret: String,
        url: String,
        description: String?
      }

    class RegisteredWebhook < ::Believe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor event_types: ::Array[::Believe::Models::RegisteredWebhook::event_type]

      attr_accessor secret: String

      attr_accessor url: String

      attr_accessor description: String?

      def initialize: (
        id: String,
        created_at: Time,
        event_types: ::Array[::Believe::Models::RegisteredWebhook::event_type],
        secret: String,
        url: String,
        ?description: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        event_types: ::Array[::Believe::Models::RegisteredWebhook::event_type],
        secret: String,
        url: String,
        description: String?
      }

      type event_type = :"match.completed" | :"team_member.transferred"

      module EventType
        extend ::Believe::Internal::Type::Enum

        MATCH_COMPLETED: :"match.completed"
        TEAM_MEMBER_TRANSFERRED: :"team_member.transferred"

        def self?.values: -> ::Array[::Believe::Models::RegisteredWebhook::event_type]
      end
    end
  end
end
