module Believe
  module Models
    type team_member_delete_params =
      { member_id: String } & ::Believe::Internal::Type::request_parameters

    class TeamMemberDeleteParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor member_id: String

      def initialize: (
        member_id: String,
        ?request_options: ::Believe::request_opts
      ) -> void

      def to_hash: -> {
        member_id: String,
        request_options: ::Believe::RequestOptions
      }
    end
  end
end
