module Believe
  module Models
    type team_member_list_response =
      Believe::Player
      | Believe::Coach
      | Believe::MedicalStaff
      | Believe::EquipmentManager

    module TeamMemberListResponse
      extend Believe::Internal::Type::Union

      def self?.variants: -> ::Array[Believe::Models::team_member_list_response]
    end
  end
end
