module Believe
  module Models
    type team_update_params =
      {
        annual_budget_gbp: Believe::Models::TeamUpdateParams::annual_budget_gbp?,
        average_attendance: Float?,
        contact_email: String?,
        culture_score: Integer?,
        founded_year: Integer?,
        is_active: bool?,
        league: Believe::Models::league?,
        name: String?,
        nickname: String?,
        primary_color: String?,
        rival_teams: ::Array[String]?,
        secondary_color: String?,
        stadium: String?,
        stadium_location: Believe::GeoLocation?,
        values: Believe::TeamValues?,
        website: String?,
        win_percentage: Float?
      }
      & Believe::Internal::Type::request_parameters

    class TeamUpdateParams < Believe::Internal::Type::BaseModel
      extend Believe::Internal::Type::RequestParameters::Converter
      include Believe::Internal::Type::RequestParameters

      attr_accessor annual_budget_gbp: Believe::Models::TeamUpdateParams::annual_budget_gbp?

      attr_accessor average_attendance: Float?

      attr_accessor contact_email: String?

      attr_accessor culture_score: Integer?

      attr_accessor founded_year: Integer?

      attr_accessor is_active: bool?

      attr_accessor league: Believe::Models::league?

      attr_accessor name: String?

      attr_accessor nickname: String?

      attr_accessor primary_color: String?

      attr_accessor rival_teams: ::Array[String]?

      attr_accessor secondary_color: String?

      attr_accessor stadium: String?

      attr_accessor stadium_location: Believe::GeoLocation?

      attr_accessor values: Believe::TeamValues?

      attr_accessor website: String?

      attr_accessor win_percentage: Float?

      def initialize: (
        ?annual_budget_gbp: Believe::Models::TeamUpdateParams::annual_budget_gbp?,
        ?average_attendance: Float?,
        ?contact_email: String?,
        ?culture_score: Integer?,
        ?founded_year: Integer?,
        ?is_active: bool?,
        ?league: Believe::Models::league?,
        ?name: String?,
        ?nickname: String?,
        ?primary_color: String?,
        ?rival_teams: ::Array[String]?,
        ?secondary_color: String?,
        ?stadium: String?,
        ?stadium_location: Believe::GeoLocation?,
        ?values: Believe::TeamValues?,
        ?website: String?,
        ?win_percentage: Float?,
        ?request_options: Believe::request_opts
      ) -> void

      def to_hash: -> {
        annual_budget_gbp: Believe::Models::TeamUpdateParams::annual_budget_gbp?,
        average_attendance: Float?,
        contact_email: String?,
        culture_score: Integer?,
        founded_year: Integer?,
        is_active: bool?,
        league: Believe::Models::league?,
        name: String?,
        nickname: String?,
        primary_color: String?,
        rival_teams: ::Array[String]?,
        secondary_color: String?,
        stadium: String?,
        stadium_location: Believe::GeoLocation?,
        values: Believe::TeamValues?,
        website: String?,
        win_percentage: Float?,
        request_options: Believe::RequestOptions
      }

      type annual_budget_gbp = Float | String

      module AnnualBudgetGbp
        extend Believe::Internal::Type::Union

        def self?.variants: -> ::Array[Believe::Models::TeamUpdateParams::annual_budget_gbp]
      end
    end
  end
end
