module Believe
  module Models
    type unwrap_webhook_event = (::Believe::MatchCompletedWebhookEvent | ::Believe::TeamMemberTransferredWebhookEvent)

    module UnwrapWebhookEvent
      extend ::Believe::Internal::Type::Union

      def self?.variants: () -> ::Array[::Believe::Models::unwrap_webhook_event]
    end
  end
end
