module Believe
  module Models
    type webhook_create_params =
      {
        url: String,
        description: String?,
        event_types: ::Array[::Believe::Models::WebhookCreateParams::event_type]?
      }
      & ::Believe::Internal::Type::request_parameters

    class WebhookCreateParams < ::Believe::Internal::Type::BaseModel
      extend ::Believe::Internal::Type::RequestParameters::Converter
      include ::Believe::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_accessor description: String?

      attr_accessor event_types: ::Array[::Believe::Models::WebhookCreateParams::event_type]?

      def initialize: (
        url: String,
        ?description: String?,
        ?event_types: ::Array[::Believe::Models::WebhookCreateParams::event_type]?,
        ?request_options: ::Believe::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        description: String?,
        event_types: ::Array[::Believe::Models::WebhookCreateParams::event_type]?,
        request_options: ::Believe::RequestOptions
      }

      type event_type = :"match.completed" | :"team_member.transferred"

      module EventType
        extend ::Believe::Internal::Type::Enum

        MATCH_COMPLETED: :"match.completed"
        TEAM_MEMBER_TRANSFERRED: :"team_member.transferred"

        def self?.values: -> ::Array[::Believe::Models::WebhookCreateParams::event_type]
      end
    end
  end
end
