module Believe
  module Resources
    class Coaching
      attr_reader principles: ::Believe::Resources::Coaching::Principles

      def initialize: (client: ::Believe::Client) -> void
    end
  end
end
